### ISSUE TITLE
Repo name is inappropriate 

### ISSUE THREAD

**Issue by Surumerf** [Tinblackstar/Robot-Lancer#9]
CLOSED

**Comment by Tinblackstar** [comment]
#include<Servo.h>
#include <stdlib.h>
const int motor1A = 2; //順回転
const int motor1B = 4; //逆回転
const int motor2A = 7;  //順回転
const int motor2B = 8;  //逆回転
const int PWM_mot1 = 11; //モーター1,2のPWM制御
const int PWM_mot2 = 3; //モーター1,2のPWM制御
Servo Servo0;
int count = 1;
int a = 500;
unsigned long time;

void setup() {
  pinMode(2, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(11, OUTPUT);
  pinMode(3, OUTPUT);
  Servo0.attach(9);
  Serial.begin(9600);
  Servo0.write(77);
}

void loop() {
  ADCSRA = ADCSRA & 0xf8;
  ADCSRA = ADCSRA | 0x04;

 /* time = millis(); //時間を計る
  Serial.println(time);
  Serial.print("\t");
  delay(1000);
  if (time >= 60000)
  {
    exit(0);
  }*/
  
  int val1, val2, val3, val4;
  val1 = analogRead(A2); //A
  val2 = analogRead(A3); //B
  val3 = analogRead(A4); //C
  val4 = analogRead(A5); //D
  // 数値の確認
  Serial.print(val1);
  Serial.print("\t");
  Serial.print(val2);
  Serial.print("\t");
  Serial.print(val3);
  Serial.print("\t");
  Serial.print(val4);
  Serial.println("");

  if ((val1 > a) && (val2 < a) && (val3 > a)/* && (val4 > a)*/)
  {
    go();
  }

  /*if ((val1 < a) && (val4 < a))
    {
    go();
    }*/

  if ((val1 < a) && (val2 > a) && (val3 > a) /*&& (val4 > a)*/) //Aのみ反応
  {
    //while (val2 > 100) {
    left();
    //}
  }

  if ((val1 > a) && (val2 > a) && (val3 < a) /*&& (val4 > a)*/) //Cのみ反応
  {
    //while (val2 > 100) {
    right();
    //}
  }

  /*  if (val1 < 200 && val2 < 200 && val3 < 200 && val4 < 200) //A,Dのみ反応
      {
       速度を少し落として前進（カーブ前だから）
        go1();
      }
  */
  /*
    if ((val1 < 200) && (val4 < 200))
    {
      go2();
    }
  */

  /*   if ((val1 > a) && (val4 < a)) //C,Dのみ反応
     {
       if (count == 1) {
         servo0();
         count++;
       } else if (count == 2) {
         servo1();
         count++;
       } else {
         servo2();
         count++;

         if (count >= 4) {
           count = 1;
         }
       }
     }*/
}


void go()
{
  digitalWrite(motor1A, LOW); //右側のモータ
  digitalWrite(motor1B, HIGH);
  analogWrite(11, 32);
  digitalWrite(motor2A, LOW); //左側のモータ
  digitalWrite(motor2B, HIGH);
  analogWrite(3, 33);
}

void go1()
{
  digitalWrite(motor1A, LOW); //右側のモータ
  digitalWrite(motor1B, HIGH);
  analogWrite(11, 30/*18*/);
  digitalWrite(motor2A, LOW); //左側のモータ
  digitalWrite(motor2B, HIGH);
  analogWrite(3, 30/*12*/);
}
/*
  void go2()
  {
  delay(1500);
  digitalWrite(motor1A, LOW); //右側のモータ
  digitalWrite(motor1B, HIGH);
  analogWrite(11, 15);
  digitalWrite(motor2A, LOW); //左側のモータ
  digitalWrite(motor2B, HIGH);
  analogWrite(3, 25);
  delay(1500);
  }*/

void left()
{
  digitalWrite(motor1A, LOW); //右側のモータ
  digitalWrite(motor1B, HIGH);
  analogWrite(11, 30/*18*/);
  digitalWrite(motor2A, LOW); //左側のモータ
  digitalWrite(motor2B, HIGH);
  analogWrite(3, 16/*12*/);
}

void right()
{
  digitalWrite(motor1A, LOW); //右側のモータ
  digitalWrite(motor1B, HIGH);
  analogWrite(11, 16/*12*/);
  digitalWrite(motor2A, LOW); //左側のモータ
  digitalWrite(motor2B, HIGH);
  analogWrite(3, 20/*16*/);
}

void right1()
{
  digitalWrite(motor1A, LOW); //右側のモータ
  digitalWrite(motor1B, HIGH);
  analogWrite(11, 20);
  digitalWrite(motor2A, LOW); //左側のモータ
  digitalWrite(motor2B, HIGH);
  analogWrite(3, 15);
}
/*
  void servo0(void)//0.25用
  {
  Servo0.write(-77);
  delay(1000);
  Servo0.write(77);
  }

  void servo1(void)//0.30用
  {
  Servo0.write(-77);
  delay(1000);
  Servo0.write(77);
  }

  void servo2(void)//0.2用
  {
  Servo0.write(-77);
  delay(1000);
  Servo0.write(77);
  }*/
void exit(int)
{
  digitalWrite(motor1A, LOW); //右側のモータ
  digitalWrite(motor1B, HIGH);
  analogWrite(11, 5);
  digitalWrite(motor2A, LOW); //左側のモータ
  digitalWrite(motor2B, HIGH);
  analogWrite(3, 5);
}
